name: Update Markdown File Count

on:
  push:
    paths:
      - '**/*.md'
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨1点自动更新

jobs:
  update-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Count .md files (excluding README.md)
        id: count
        run: |
          count=$(find . -maxdepth 1 -name '*.md' ! -name 'README.md' | wc -l)
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          count=${{ steps.count.outputs.count }}
          sed -i -E "s/(<!-- COUNT_START -->)[0-9]+(<!-- COUNT_END -->)/\1$count\2/" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update file count"
          git push
